services:

  mongodb:
    container_name: ms_mongo_db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: e-commerce
      MONGO_INITDB_ROOT_PASSWORD: e-commerce

  mongo-express:
    container_name: ms_mongo_express
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: e-commerce
      ME_CONFIG_MONGODB_ADMINPASSWORD: e-commerce
      ME_CONFIG_MONGODB_SERVER: mongodb

volumes:
  mongo: